//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDocumentation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Course title")]
        public string COURSE_TITLE_STRING {
            get {
                return ((string)(this["COURSE_TITLE_STRING"]));
            }
            set {
                this["COURSE_TITLE_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Subject / Sub topic</string>
  <string>Lesson / Topic</string>
  <string>Lesson / Topic / Sub-Topic</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SUBJECT_DIVIDERS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SUBJECT_DIVIDERS"]));
            }
            set {
                this["SUBJECT_DIVIDERS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Subject</string>\r\n  <string>Lesson</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SUBJECT_TOPIC_NAMING {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SUBJECT_TOPIC_NAMING"]));
            }
            set {
                this["SUBJECT_TOPIC_NAMING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Part")]
        public string PART_DIVIDER {
            get {
                return ((string)(this["PART_DIVIDER"]));
            }
            set {
                this["PART_DIVIDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Front page 1")]
        public string TITLE_SLIDE {
            get {
                return ((string)(this["TITLE_SLIDE"]));
            }
            set {
                this["TITLE_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("equipment")]
        public string TITLE_SLIDE_MAIN_TITLE_KEYWORD {
            get {
                return ((string)(this["TITLE_SLIDE_MAIN_TITLE_KEYWORD"]));
            }
            set {
                this["TITLE_SLIDE_MAIN_TITLE_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lesson name")]
        public string TITLE_SLIDE_SUBTITLE_KEYWORD {
            get {
                return ((string)(this["TITLE_SLIDE_SUBTITLE_KEYWORD"]));
            }
            set {
                this["TITLE_SLIDE_SUBTITLE_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("**Instructor notes should go in between these asterisks**")]
        public string DEFAULT_NOTES_TEXT {
            get {
                return ((string)(this["DEFAULT_NOTES_TEXT"]));
            }
            set {
                this["DEFAULT_NOTES_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome!")]
        public string DEFAULT_TITLE_SLIDE_NOTES {
            get {
                return ((string)(this["DEFAULT_TITLE_SLIDE_NOTES"]));
            }
            set {
                this["DEFAULT_TITLE_SLIDE_NOTES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Notes:")]
        public string DEFAULT_NOTES_ENDING {
            get {
                return ((string)(this["DEFAULT_NOTES_ENDING"]));
            }
            set {
                this["DEFAULT_NOTES_ENDING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*h1*")]
        public string HEADING1_MARKUP {
            get {
                return ((string)(this["HEADING1_MARKUP"]));
            }
            set {
                this["HEADING1_MARKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*h2*")]
        public string HEADING2_MARKUP {
            get {
                return ((string)(this["HEADING2_MARKUP"]));
            }
            set {
                this["HEADING2_MARKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*h3*")]
        public string HEADING3_MARKUP {
            get {
                return ((string)(this["HEADING3_MARKUP"]));
            }
            set {
                this["HEADING3_MARKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("- RIG NAME -")]
        public string DEFAULT_TITLE_SLIDE_SUBTITLE {
            get {
                return ((string)(this["DEFAULT_TITLE_SLIDE_SUBTITLE"]));
            }
            set {
                this["DEFAULT_TITLE_SLIDE_SUBTITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Introduction")]
        public string INTRODUCTION_SUBJECT_TITLE {
            get {
                return ((string)(this["INTRODUCTION_SUBJECT_TITLE"]));
            }
            set {
                this["INTRODUCTION_SUBJECT_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Introduction")]
        public string INTRODUCTION_SLIDE {
            get {
                return ((string)(this["INTRODUCTION_SLIDE"]));
            }
            set {
                this["INTRODUCTION_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lesson goal")]
        public string LESSON_GOAL_SLIDE {
            get {
                return ((string)(this["LESSON_GOAL_SLIDE"]));
            }
            set {
                this["LESSON_GOAL_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Then you have obtained")]
        public string LESSON_GOAL_OBTAINED_SLIDE {
            get {
                return ((string)(this["LESSON_GOAL_OBTAINED_SLIDE"]));
            }
            set {
                this["LESSON_GOAL_OBTAINED_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add lesson goal")]
        public string LESSON_GOAL_SLIDE_CONTAINER_KEYWORD {
            get {
                return ((string)(this["LESSON_GOAL_SLIDE_CONTAINER_KEYWORD"]));
            }
            set {
                this["LESSON_GOAL_SLIDE_CONTAINER_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lesson goal")]
        public string LESSON_GOAL_SLIDE_TITLE {
            get {
                return ((string)(this["LESSON_GOAL_SLIDE_TITLE"]));
            }
            set {
                this["LESSON_GOAL_SLIDE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Review of lesson goal")]
        public string LESSON_GOAL_OBTAINED_SLIDE_TITLE {
            get {
                return ((string)(this["LESSON_GOAL_OBTAINED_SLIDE_TITLE"]));
            }
            set {
                this["LESSON_GOAL_OBTAINED_SLIDE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lesson objectives")]
        public string LESSON_OBJECTIVES_SLIDE {
            get {
                return ((string)(this["LESSON_OBJECTIVES_SLIDE"]));
            }
            set {
                this["LESSON_OBJECTIVES_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("By now, you are able to")]
        public string LESSON_OBJECTIVES_REVIEW_SLIDE {
            get {
                return ((string)(this["LESSON_OBJECTIVES_REVIEW_SLIDE"]));
            }
            set {
                this["LESSON_OBJECTIVES_REVIEW_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add lesson objectives")]
        public string LESSON_OBJECTIVES_SLIDE_CONTAINER_KEYWORD {
            get {
                return ((string)(this["LESSON_OBJECTIVES_SLIDE_CONTAINER_KEYWORD"]));
            }
            set {
                this["LESSON_OBJECTIVES_SLIDE_CONTAINER_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lesson objectives")]
        public string LESSON_OBJECTIVES_SLIDE_TITLE {
            get {
                return ((string)(this["LESSON_OBJECTIVES_SLIDE_TITLE"]));
            }
            set {
                this["LESSON_OBJECTIVES_SLIDE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Review of lesson objectives")]
        public string LESSON_OBJECTIVES_REVIEW_SLIDE_TITLE {
            get {
                return ((string)(this["LESSON_OBJECTIVES_REVIEW_SLIDE_TITLE"]));
            }
            set {
                this["LESSON_OBJECTIVES_REVIEW_SLIDE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic divider")]
        public string TOPIC_DIVIDER_SLIDE {
            get {
                return ((string)(this["TOPIC_DIVIDER_SLIDE"]));
            }
            set {
                this["TOPIC_DIVIDER_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add topic title")]
        public string TOPIC_DIVIDER_SLIDE_CONTAINER_KEYWORD {
            get {
                return ((string)(this["TOPIC_DIVIDER_SLIDE_CONTAINER_KEYWORD"]));
            }
            set {
                this["TOPIC_DIVIDER_SLIDE_CONTAINER_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("**")]
        public string INSTRUCTOR_NOTES_MARKUP {
            get {
                return ((string)(this["INSTRUCTOR_NOTES_MARKUP"]));
            }
            set {
                this["INSTRUCTOR_NOTES_MARKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic objective: ")]
        public string TOPIC_DIVIDER_TOPIC_OBJECTIVE {
            get {
                return ((string)(this["TOPIC_DIVIDER_TOPIC_OBJECTIVE"]));
            }
            set {
                this["TOPIC_DIVIDER_TOPIC_OBJECTIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic methods and/or activities: ")]
        public string TOPIC_DIVIDER_TOPIC_METHODS {
            get {
                return ((string)(this["TOPIC_DIVIDER_TOPIC_METHODS"]));
            }
            set {
                this["TOPIC_DIVIDER_TOPIC_METHODS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic evaluation: ")]
        public string TOPIC_DIVIDER_TOPIC_EVALUATION {
            get {
                return ((string)(this["TOPIC_DIVIDER_TOPIC_EVALUATION"]));
            }
            set {
                this["TOPIC_DIVIDER_TOPIC_EVALUATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic time: ")]
        public string TOPIC_DIVIDER_TOPIC_TIME {
            get {
                return ((string)(this["TOPIC_DIVIDER_TOPIC_TIME"]));
            }
            set {
                this["TOPIC_DIVIDER_TOPIC_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic materials: ")]
        public string TOPIC_DIVIDER_TOPIC_MATERIALS {
            get {
                return ((string)(this["TOPIC_DIVIDER_TOPIC_MATERIALS"]));
            }
            set {
                this["TOPIC_DIVIDER_TOPIC_MATERIALS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topic notes: ")]
        public string TOPIC_DIVIDER_TOPIC_NOTES {
            get {
                return ((string)(this["TOPIC_DIVIDER_TOPIC_NOTES"]));
            }
            set {
                this["TOPIC_DIVIDER_TOPIC_NOTES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REGULAR SLIDE")]
        public string CONTENT_SLIDE {
            get {
                return ((string)(this["CONTENT_SLIDE"]));
            }
            set {
                this["CONTENT_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("title style")]
        public string CONTENT_SLIDE_TITLE_CONTAINER_KEYWORD {
            get {
                return ((string)(this["CONTENT_SLIDE_TITLE_CONTAINER_KEYWORD"]));
            }
            set {
                this["CONTENT_SLIDE_TITLE_CONTAINER_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text styles")]
        public string CONTENT_SLIDE_CONTENT_CONTAINER_KEYWORD {
            get {
                return ((string)(this["CONTENT_SLIDE_CONTENT_CONTAINER_KEYWORD"]));
            }
            set {
                this["CONTENT_SLIDE_CONTENT_CONTAINER_KEYWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TO DO: add content...")]
        public string CONTENT_SLIDE_DEFAULT_CONTENT {
            get {
                return ((string)(this["CONTENT_SLIDE_DEFAULT_CONTENT"]));
            }
            set {
                this["CONTENT_SLIDE_DEFAULT_CONTENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Question slide")]
        public string QUESTIONS_SLIDE {
            get {
                return ((string)(this["QUESTIONS_SLIDE"]));
            }
            set {
                this["QUESTIONS_SLIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Questions?")]
        public string QUESTIONS_SLIDE_TITLE {
            get {
                return ((string)(this["QUESTIONS_SLIDE_TITLE"]));
            }
            set {
                this["QUESTIONS_SLIDE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17.5")]
        public float HANDBOOK_MAX_SLIDE_WIDTH {
            get {
                return ((float)(this["HANDBOOK_MAX_SLIDE_WIDTH"]));
            }
            set {
                this["HANDBOOK_MAX_SLIDE_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*hbyes*")]
        public string FORCE_SLIDE_HANDBOOK_YES {
            get {
                return ((string)(this["FORCE_SLIDE_HANDBOOK_YES"]));
            }
            set {
                this["FORCE_SLIDE_HANDBOOK_YES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*hbno*")]
        public string FORCE_SLIDE_HANDBOOK_NO {
            get {
                return ((string)(this["FORCE_SLIDE_HANDBOOK_NO"]));
            }
            set {
                this["FORCE_SLIDE_HANDBOOK_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.62")]
        public double TWO_SLIDES_ON_PAGE_FACTOR {
            get {
                return ((double)(this["TWO_SLIDES_ON_PAGE_FACTOR"]));
            }
            set {
                this["TWO_SLIDES_ON_PAGE_FACTOR"] = value;
            }
        }
    }
}
